[Env][Conda] pin acpp and clang versions (#875)
I had to pin the version of acpp and clang because conda is so trash
that requiring an env with acpp and clangxx create something that has to
following error because of mismatched llvm versions

```
error: unable to load plugin '/opt/conda/envs/shamrock_dev_environment/bin/../lib/libacpp-clang.so': '/opt/conda/envs/shamrock_dev_environment/bin/../lib/libacpp-clang.so: undefined symbol: _ZN4llvm9DIBuilder23insertDbgValueIntrinsicEPNS_5ValueEPNS_15DILocalVariableEPNS_12DIExpressionEPKNS_10DILocationEPNS_11InstructionE'
```